### ISSUE TITLE
--update-pr issue with multilevel Fork structure

### ISSUE THREAD

**Issue by shahzebsiddiqui** [easybuilders/easybuild-framework#2418] opened 2018-03-01 17:00 UTC
We have a fork of easybuild-easyconfig in organization PfizerRD and I have my fork from PfizerRD.

See https://github.com/PfizerRD/easybuild-easyconfigs and https://github.com/shahzebsiddiqui/easybuild-easyconfigs 

My git remotes are the following, and I am cloning from origin

```
[siddis14@amrndhl1157 DAAL]$ git remote -v
easybuilders    git@github.com:easybuilders/easybuild-easyconfigs.git (fetch)
easybuilders    git@github.com:easybuilders/easybuild-easyconfigs.git (push)
origin  git@github.com:shahzebsiddiqui/easybuild-easyconfigs.git (fetch)
origin  git@github.com:shahzebsiddiqui/easybuild-easyconfigs.git (push)
upstream        git@github.com:PfizerRD/easybuild-easyconfigs.git (fetch)
upstream        git@github.com:PfizerRD/easybuild-easyconfigs.git (push)
```

My github easybuild is configured to push to origin 

```
[siddis14@amrndhl1157 DAAL]$ eb --check-github
== temporary log file in case of crash /tmp/eb-h_dQfs/easybuild-UnX_RQ.log

Checking status of GitHub integration...

Making sure we're online...OK

* GitHub user...shahzebsiddiqui => OK
* GitHub token...625..998 (len: 40) => OK (validated)
* git command...OK ("git version 1.8.3.1; ")
* GitPython module...OK (GitPython version 2.1.5)
* push access to shahzebsiddiqui/easybuild-easyconfigs repo @ GitHub...OK
* creating gists...OK
* location to Git working dirs... not found (suboptimal)

All checks PASSed!

Status of GitHub integration:
* --from-pr: OK
* --new-pr: OK
* --review-pr: OK
* --update-pr: OK
* --upload-test-report: OK

```

I have a PR https://github.com/easybuilders/easybuild-easyconfigs/pull/4825 that was pushed from PfizerRD:eb-daal branch.

When I run 

```
eb --update-pr 4825 --pr-commit-msg "adding sha256 and fix few issues requested by @boegel" DAAL-2017.1.132.eb

```

The commit went to https://github.com/shahzebsiddiqui/easybuild-easyconfigs/commit/3ceb18b0c4854a3a816050b4d2b240532e412c42 and it did not update the PR since the branch eb-daal was not linked from origin to upstream. The PR is from upstream to easybuilders remote endpoint

```
[siddis14@amrndhl1157 DAAL]$ eb -ld --update-pr 4825 --pr-commit-msg "adding sha256 and fix few issues requested by @boegel" DAAL-2017.1.132.eb | grep "Pushing branch"
ERROR: No changed files found when comparing to current develop branch. Refused to make empty pull request.

```

**Comment by boegel** [comment] 2018-03-01 17:08
@shahzebsiddiqui I think the problem is that `--update-pr` pushes the updated branch to whatever account you have specified in `--github-org` or `--github-user` (in your case `shahzebsiddiqui`), rather than the account/organisation where the branch relating to the PR lives (in your case `PfizerRD`).

Can you check whether this change fixes your problem? Basically change `github_account` to `target_account` in the `_easyconfigs_pr_common` function in `easybuild/tools/github.py` in your EasyBuild installation.

```diff
diff --git a/easybuild/tools/github.py b/easybuild/tools/github.py
index c4c035d8e..841887a3f 100644
--- a/easybuild/tools/github.py
+++ b/easybuild/tools/github.py
@@ -769,10 +769,9 @@ def _easyconfigs_pr_common(paths, ecs, start_branch=None, pr_branch=None, target
     git_repo.index.commit(commit_msg)
 
     # push to GitHub
-    github_account =  build_option('github_org') or build_option('github_user')
-    github_url = 'git@github.com:%s/%s.git' % (github_account, pr_target_repo)
+    github_url = 'git@github.com:%s/%s.git' % (target_account, pr_target_repo)
     salt = ''.join(random.choice(string.letters) for _ in range(5))
-    remote_name = 'github_%s_%s' % (github_account, salt)
+    remote_name = 'github_%s_%s' % (target_account, salt)
 
     dry_run = build_option('dry_run') or build_option('extended_dry_run')
 
```

**Comment by boegel** [comment] 2018-03-02 08:14
fixed in #2419

**Closed by boegel** 2018-03-02 08:14 UTC
Labels: bug report

**Comment by shahzebsiddiqui** [comment] 2018-03-02 19:35
@boegel i see this is merged, looks fine with me.

**Comment by boegel** [comment] 2018-03-02 19:41
Well, the downside is that I introduced a bug in #2419, which breaks `--new-pr` in EasyBuild v3.5.2, see #2423 ... :(
