### ISSUE TITLE
Skip sanity check step

### ISSUE THREAD

**Issue by lucamar** [easybuilders/easybuild-framework#1626] opened 2016-02-19 18:42 UTC
Hi,
I've tried to skip the sanity check step of a python package (GPAW) that uses the easyblock pythonpackage.py, but I could not manage to let EasyBuild skip that step.
I've tried using the following in the easyconfig:
skipsteps = ['install', 'sanitycheck']
It skips the install step, but not the sanity check. Changing the spelling to "sanity_check" did not help either, as it seems that the sanity_check step is treated differently with respect to the configuration, build, etc...
Thanks for any advice.
Luca

**Comment by boegel** [comment] 2016-02-19 18:45
@lucamar: some steps are not skippable, including the sanity check step...

Why are you trying to skip the sanity check step? Because it's failing? There's probably a good reason for it...

You can try to redefine `sanity_check_paths` if you're sure the installation is what it should be; you may need to redefine other things to make the sanity check happy.

**Comment by lucamar** [comment] 2016-02-19 18:53
It fails due to the issue with Python provided by Easybuild and MPI on the Cray systems. 
The issue will be solved in a future release, but it would be convenient in general to be able to skip the sanity check as for other steps.
Otherwise one has to manually change/redefine other elements, as you suggest, which is not as straightforward as defining "skipsteps = ['sanitycheck']" in the easyconfig file (provided that one knows that the installation is fine).

**Comment by gppezzi** [comment] 2016-02-22 15:19
Does this mean that the sanity check in this case assumes that you are on a compute node (or have a working MPI environment)?

How about doing the sanity check through the batch system? would it be hard to implement?

**Comment by pforai** [comment] 2016-02-23 13:43
@gppezzi Yeah, it basically expects that your system looks like the one EB was designed on, ie wherever you build things on allows you to run whatever you built before, a separation of building and running tests/executing as is standard on very large installations (Cray, BlueGene, etc.) is not supported right now.

One would need to implement the run_cmd() function to make use of GC3Pie and execute the sanity check through a DRM as well a specify maximum time outs (or use sane defaults).

**Comment by boegel** [comment] 2017-02-24 13:50
@lucamar does you closing the issue mean you no longer require the ability to skip the sanity check?

**Comment by lucamar** [comment] 2017-02-24 14:31
@boegel I've seen that you had added this issue to v2.x and we have now 3.0.2

**Comment by boegel** [comment] 2017-02-24 15:03
@lucamar the milestone was later bumped to v3.x, i.e. being able to skip the sanity check hasn't been implemented yet...

**Comment by lucamar** [comment] 2017-02-24 15:12
@boegel I see: to be honest haven't tried that any longer. If you think that it is feasible to have it as a feature, then I'll reopen the issue

**Comment by boegel** [comment] 2017-02-24 15:18
@lucamar Well, it's feasible, sure, but I don't know how smart it is to support it.

I do understand that it's frustrating to not be able to skip the sanity check, but I would like to somehow avoid that people start doing it all the time.

There's a very good reason the sanity check is there, but clearly there are corner cases where it breaks for the wrong reasons...

Your view @gppezzi?

**Comment by DanielTosello** [comment] 2017-03-07 02:56
This would be extremely useful for developing new easyblocks & configs (and contributing them back without feeling like they're horribly messy)

**Comment by avapirev** [comment] 2017-04-03 10:13
I would love to be able to skip the sanity checks. In 100% of the cases (my cases) the fails are due to differences in the file/direcotries locations for different versions of the software I install and not in errors of the installation itself. That is, the files are there and they do work as expected, but the sanity check expects them to be somewhere else. An example - OpenFOAMv4: file named 'vorticity' is there, just not in the place where EB looks for it. This results of days (literary) wasted build time until the proper sanity check options are found. Regards.

**Comment by wpoely86** [comment] 2017-04-03 10:34
@avapirev How will you know if your build is really broken or just a file in a different location?
It's better to make the sanity checks smart. What do you do to make to files be at different locations?

**Comment by avapirev** [comment] 2017-04-03 10:44
@wpoely86 And how do you define a "broken build"? Configure. Check. Compile. Check. Install. Check. Ask for trouble (sanity). Check (read "Failed"). As I said, that is my experience. Other users may have different opinion and I respect that of course. Cheers.

**Comment by wpoely86** [comment] 2017-04-03 10:50
I know how annoying it is when a build fails in the sanity check (especially when it's ParaView and takes 3h to compile). 

My point is if you skip the sanity check, how will you know that `vorticity` is there or not? The OpenFOAM build procedure is crazy enough to continue even if something fails. 

I'm more interested why some binaries end up in a different place for you.

**Comment by paulmelis** [comment] 2017-10-04 12:48
Having just battled the forced sanity checks myself, here my 2 cents. 

I feel what is not clear here, and it's what I read in @avapirev's and @DanielTosello's comments as well, is the difference between having the sanity checks in place during a regular EB build and install (where it obviously makes sense) versus during *development of an EB config script* (where you might sometimes want to leave out the sanity checks until it's clear what EB is actually installing and where). 

The process of turning a "classical" build process that you know (shell scripts, manual configure/make steps, etc.) into a full EB workflow isn't as straightforward as I hoped and I find myself frequently trying to figure out what EB is doing. Maybe it is mostly useful while still learning EB, but it feels a bit overly protective to not allow a developer to write EB configs that do what he/she wants (i.e. currently setting both `sanity_check_paths['files']` and `sanity_check_paths['dirs']` to `[]` is not allowed), when there might be good reasons for it.

You could argue that EB configs in the official EB repo must have certain characteristics, such as containing sanity checks. However, even those can be done poorly, e.g. listing only one binary file out of ten, just to keep the sanity checks happy.

**Comment by damianam** [comment] 2018-08-17 14:19
Well, I just hit this issue as well. Our example: `h5py` tries to run within a MPI environment when imported. In login nodes MPI doesn't work. In compute nodes, we don't allow to run MPI programs within an `srun` instance. I honestly don't see why `skipsteps = ['sanity_check']` should be ignored. For sure it is not smart to just drop that in every easyconfig but if the site configuration requires it in certain instances..... why not allow it?

**Comment by akesandgren** [comment] 2018-08-17 16:10
If you are developing a easyconfig/easyblock and want to check where files/dirs end up before writing a working sanity check, why not use --stop=postproc ? That's before sanity checking and you can verify where everything is. And if need be add --disable-cleanup-tmpdir --disable-cleanup-builddir if needed. (Can't remember exactly when/if they are triggered when running with --stop)

@damianam If mpirun doesn't work on your login nodes then your mpi setup is broken, and srun is a replacement for mpirun so what's the problem there? Are you trying to do something similar to "srun ... mpirun ..."??

**Comment by boegel** [comment] 2018-08-18 21:02
Support for skipping the sanity check via `skipsteps` is implemented in #2549, feedback welcome.

Note that when the sanity check fails at the very end, you should be able to just fix the sanity check and then complete the installation without restarting it from scratch using `--module-only` (see also https://easybuild.readthedocs.io/en/latest/Partial_installations.html#only-re-generating-additional-module-files-using-module-only).
In fact, that's what I usually do when composing easyconfigs for new software: start with a bogus `sanity_check_paths` (`[]` for both `files` and `dirs`), let the sanity check fail, and then correct `sanity_check_paths` and complete the installation using `--module-only`.

Of course, this doesn't cover all use cases, so I ran out of arguments to not support skipping the sanity check step, hence PR #2549...

**Comment by damianam** [comment] 2018-08-20 17:08
> If mpirun doesn't work on your login nodes then your mpi setup is broken

Is it? I can think of a couple of reasons why that is not true. In our case it was "broken by accident". The MPI runtime expected to find infiniband devices, which where not present (the login nodes are running in a container that doesn't have the infiniband devices available at the moment). It was a byproduct of the setup, not an intended effect AFAIK. MPI runs just fine when launched in a parallel environment (ie: within a job). But I wouldn't object to not allowing `mpirun` to launch jobs in a login node.....

No, I wasn't trying to run `srun mpirun` or anything similar. `import h5py` calls `mpi4py` which calls `MPI_Init` which was failing due to the lack of infiniband devices.

Alternatively, getting an interactive session with `srun --mpi=none` did the trick in my case. I wasn't aware of that option. Without it the parallel environment gets set, and it fails when trying to initialize an MPI job within that session.

**Comment by akesandgren** [comment] 2018-08-20 17:42
There is a difference between "not working" and "not allowing". I was assuming you meant the former.

And what MPI runtime are we talking about? OpenMPI? It is supposed to work even if such things as IB drivers are missing even if it is built with IB support. If it doesn't then I think they would classify that as a bug.

**Comment by boegel** [comment] 2018-09-04 16:02
Closing this since https://github.com/easybuilders/easybuild-framework/pull/2549 has been merged, to be included in the upcoming EasyBuild 3.7.0...

**Closed by boegel** 2018-09-04 16:02 UTC
Labels: change request
