### ISSUE TITLE
builddir not set correctly when build_in_installdir = True and running --sanity-check-only

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild-framework#3895] opened 2021-11-09 12:37 UTC
When `self.build_in_installdir = True` (c.f. OpenFOAM easyblock) and running `--sanity-check-only` then `self.builddir` is not set correctly.

Error:
```
cd: /dev/shm/build-branfosj-admin/branfosj-admin-up/OpenFOAM/8/foss-2020b: No such file or directory
```

That corresponds to
```
buildpath                 (E) = /dev/shm/build-branfosj-admin/branfosj-admin-up
```

**Comment by boegel** [comment] 2021-11-19 08:12
The problem is that `self.builddir = self.installdir` is only set in `make_builddir`, which is part of the `ready` step (that is skipped entirely when using `--sanity-check-only`).

Fixed in #3900 by moving `self.builddir = self.installdir` to the `EasyBlock` constructor, so it's always done, regardless of which steps are run.

**Closed** 2021-12-07 19:40 UTC
Labels: bug report
