### ISSUE TITLE
Default intel-2021a.eb installation failed in a HierarchicalMNS configuration 

### ISSUE THREAD

**Issue by TonyDelforge** [easybuilders/easybuild-framework#3775] opened 2021-07-13 13:14 UTC
Hello,

eb --robot intel-2021a.eb trigger the following error in a HierarchicalMNS configuration :  unknown module "impi/2021.2.0.

== preparing...
== FAILED: Installation ended unsuccessfully (build directory: <prefix>/build/iimpi/2021a/system-system): build failed (first 300 chars): Module command '/usr/share/lmod/lmod/libexec/lmod python load impi/2021.2.0' failed with exit code 1; stderr: Lmod a détecté l'erreur suivante : Le ou les module(s) suivants sont inconnus: "impi/2021.2.0"

Unfortunately, impi is installed :

eb -D intel-2021a.eb

[x] $CFGS/i/impi/impi-2021.2.0-intel-compilers-2021.2.0.eb (module: Compiler/intel-compilers/2021.2.0 | impi/2021.2.0)
[ ] $CFGS/i/iimpi/iimpi-2021a.eb (module: Core | iimpi/2021a)
[ ] $CFGS/i/imkl/imkl-2021.2.0-iimpi-2021a.eb (module: MPI/intel-compilers/2021.2.0/impi/2021.2.0 | imkl/2021.2.0)
[ ] $CFGS/i/intel/intel-2021a.eb (module: Core | intel/2021a)

I believe this error come from the MODULEPATH variable set within intel-compilers/2021.2.0 :
"prepend_path("MODULEPATH","<prefix>/modules/all/Compiler/**intel**/2021.2.0")". Since every software installed with the **intel-compilers** toolchain will be installed in <prefix>/software/Compiler/**intel-compilers**/2021.2.0 and the corresponding modules in 
prefix>/modules/all/Compiler/**intel-compilers**/2021.2.0.

Could be this issue come from the method "det_module_subdir(self, ec)" within "easybuild/tools/module_naming_scheme/hierarchical_mns.py" script ?

Best regards,
Tony

**Comment by TonyDelforge** [comment] 2021-07-13 13:41
After a test, the following minor patch seems to fix the issue :

--- <prefix>/easybuild/software/EasyBuild/4.4.0/lib/python2.7/site-packages/easybuild/tools/module_naming_scheme/hierarchical_mns_ori.py	2021-07-13 15:36:58.767143000 +0200
+++ <prefix>/easybuild/software/EasyBuild/4.4.0/lib/python2.7/site-packages/easybuild/tools/module_naming_scheme/hierarchical_mns.py	2021-07-13 15:38:13.412054000 +0200
@@ -55,7 +55,7 @@
     'icc,ifort': ('intel', '%(icc)s'),
     'iccifort': ('intel', '%(iccifort)s'),
     # required for use of intel-compilers toolchain (OneAPI compilers)
-    'intel-compilers': ('intel', '%(intel-compilers)s'),
+    'intel-compilers': ('intel-compilers', '%(intel-compilers)s'),
     # required for use of ClangGCC toolchain
     'Clang,GCC': ('Clang-GCC', '%(Clang)s-%(GCC)s'),
     # required for use of gcccuda toolchain, and for CUDA installed with GCC toolchain

**Comment by Micket** [comment] 2021-07-13 22:02
This was fixed in https://github.com/easybuilders/easybuild-framework/pull/3745
The problem is the install directory, not the modulepath. You need to update to EB 4.4.1, if anything was successfully installed there you'll need to rebuild that.

**Closed by Micket** 2021-07-13 22:02 UTC
Labels: problem report
