### ISSUE TITLE
sanity_check does not load the temporary module if there is a system one that exists already when using HMNS

### ISSUE THREAD

**Issue by mboisson** [easybuilders/easybuild-framework#2499] opened 2018-05-04 15:27 UTC
Ran into that problem testing
https://github.com/easybuilders/easybuild-easyblocks/pull/594

You can see in that gist that `/cvmfs/soft.computecanada.ca/easybuild/modules/2017/avx2/MPI/intel2016.4/openmpi2.1/lammps-omp/20170811.lua` 
is loaded instead of loading the temporary one 
`/tmp/eb-oNdpYJ/tmpRugaDe/avx2/MPI/intel2016.4/openmpi2.1/lammps-omp/20170811.lua` 

https://gist.github.com/mboisson/408d3df6335276f87fb8428bc93b386f

**Comment by mboisson** [comment] 2018-05-04 15:27
Tagging @boegel

**Comment by boegel** [comment] 2018-05-04 15:34
I need to look into this in more detail, but I think this is a bug in framework...

Have you ever seen this popping up @damianam or @ocaisa?

**Comment by ocaisa** [comment] 2018-05-07 12:00
What version of Lmod are you using? The temporary path should be the last `module use` statement. Do you have a module that adds modulepaths? A (somehow triggered) unload/load of such a module could put the system one back at the front of the path.

**Comment by mboisson** [comment] 2018-05-07 12:37
We're using Lmod 7.7.4. 

We do use a hierarchical module schema, so yes, the compiler, MPI and Cuda modules all add to the modulepath. 

Lmod offers a way to deal with module path priority however. 
Something like : 
module use --priority=1000000 /tmp/...

should do it to ensure that this module is the one that is being used.

**Comment by ocaisa** [comment] 2018-05-07 13:07
This problem doesn't really ring any bells but there quite a few configuration possibilities for the hierarchies that might trigger a reload, the temporary `priority` option to Lmod  seems like a straightforward way to sidestep this issue.

**Comment by boegel** [comment] 2018-05-22 09:39
After taking a closer look at this, I'm wondering whether this is a bug in Lmod, I'm not sure...

Here's what's going on with a hierarchical module naming scheme, assuming that we're (re)installing `foo/1.2.3` with `foss/2018a` (via `load_fake_module` in `easyblock.py`):

* `eb` generates a temporary module in `/tmp`, say `/tmp/ebtmp/modules/all/foo/1.2.3.lua`
* `eb` does a `ml use /tmp/ebtmp/modules/all` so `foo/1.2.3` can be loaded
* `eb` runs `module load foo/1.2.3` to load that temporary module file
* Lmod starts loading the `foo/1.2.3` module, and runs into load statements for both `GCCcore` and `OpenMPI` in that module file, so it starts loading those
* by loading `GCCcore` and `OpenMPI`, additional paths are prepended to `$MODULEPATH`, e.g. `/prefix/Core/GCCcore/6.4.0/modules/all` and `/prefix/Compiler/GCCcore/6.4.0/OpenMPI/2.1.2/modules/all`
* Lmod finds the `foo/1.2.3` module in one of those locations, and end up actually loading that module file rather than the one in `/tmp/ebtmp/modules/all`...

So Lmod ends up loading a different module than the one originally intended because `$MODULEPATH` gets changed along the way...

@ocaisa's suggestion to leverage `--priority` for the `module use` is a good idea, and it should fix the issue, but I'm wondering whether this is intended behavior or not by Lmod...

@rtmclay: Thoughts on this?

**Comment by boegel** [comment] 2018-05-22 13:30
@mboisson Can you check whether the proposed changes in #2506 fix the problem for you?

**Comment by rtmclay** [comment] 2018-05-22 13:43
This is expected Lmod behavior.  You need to mark foo/1.2.3 as the default in /tmp/ebtmp/...

**Comment by boegel** [comment] 2018-05-22 14:37
@rtmclay How is that going to help if the other module file is also marked as default? It won't, right?

**Comment by rtmclay** [comment] 2018-05-22 20:35
Probably not.  The only safe solution is to use priority path on MODULEPATH for /tmp/ebtmp/... 

But you should also mark it as a default because if foo/1.2.3 in two places then the one that is marked default will be picked.

**Comment by boegel** [comment] 2018-05-23 09:33
Thanks a lot for the feedback @rtmclay!

For future reference: see https://lmod.readthedocs.io/en/latest/060_locating.html

**Comment by boegel** [comment] 2018-05-23 12:37
Fixed with #2506

**Closed by boegel** 2018-05-23 12:37 UTC
Labels: bug report
