### ISSUE TITLE
--try-toolchain creates a non-compliant easyconfig

### ISSUE THREAD

**Issue by JackPerdue** [easybuilders/easybuild-framework#3100] opened 2019-11-25 16:17 UTC
See: https://github.com/easybuilders/easybuild-easyconfigs/issues/9370

**Comment by boegel** [comment] 2019-11-25 16:29
closing as duplicate of #3101 (which is the easyconfig issue I moved to framework)

**Closed by boegel** 2019-11-25 16:29 UTC
Labels: bug report
