### ISSUE TITLE
Lmod not detected by bootstrap on Fedora 23

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-framework#1500] opened 2015-12-04 23:13 UTC
Trying to bootstrap EB 2.4.0 on a Fedora 23 machine.

Lmod is installed via the Fedora RPM:

```
[adam@marcel Downloads]$ rpm -q Lmod
Lmod-6.0.15-2.fc23.noarch
```

Note that $LMOD_CMD is set:

```
env | grep LMOD
LMOD_DEFAULT_MODULEPATH=/etc/modulefiles:/usr/share/modulefiles:/usr/share/Modules/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core
LMOD_PKG=/usr/share/lmod/lmod
LMOD_VERSION=6.0.15
LMOD_sys=Linux
LMOD_PREPEND_BLOCK=normal
LMOD_SETTARG_CMD=:
LMOD_PAGER=more
LMOD_CMD=/usr/share/lmod/lmod/libexec/lmod
LMOD_arch=x86_64
LMOD_FULL_SETTARG_SUPPORT=no
LMOD_DIR=/usr/share/lmod/lmod/libexec
LMOD_COLORIZE=yes
BASH_FUNC_module()=() {  eval $($LMOD_CMD bash "$@");
 [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
BASH_FUNC_ml()=() {  eval $($LMOD_DIR/ml_cmd "$@")
```

```
[adam@marcel Downloads]$ type module
module is a function
module ()
{
    eval $($LMOD_CMD bash "$@");
    [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
```

According to the documentation at:

http://easybuild.readthedocs.org/en/latest/Installation.html#required-modules-tool

the $LMOD_CMD setting should be picked up. However, this is what happens when I run the bootstrap script:

```
[adam@marcel Downloads]$ python bootstrap_eb.py $PREFIX
[[INFO]] Installation prefix /home/adam/.local/easybuild
[[DEBUG]] Going to use /tmp/tmpAD4vyg as temporary directory
[[DEBUG]] Output from modulecmd python help: sh: modulecmd: command not found

[[DEBUG]] Output from lmod python help: sh: lmod: command not found

[[DEBUG]] Output from modulecmd.tcl python help: sh: modulecmd.tcl: command not found

[[ERROR]] Could not find any module command, make sure one available in your $PATH.
Known module commands are checked in order, and include: modulecmd, lmod, modulecmd.tcl
Check the output of 'type module' to determine the location of the module command you are using.
```

Is the documentation wrong?

**Comment by fgeorgatos** [comment] 2015-12-05 00:26
if this is the same issue like one case I have seen before for Lmod via epel repo, 
`modulecmd` may not be properly visible in $PATH. Unfortunately, this is required for bootstrap to occur.

**Comment by boegel** [comment] 2015-12-05 07:50
@verdurin: the problem is that the framework is aware of `$LMOD_CMD`, but the bootstrap script is not; if you (temporarily) include the path to `lmod` in `$PATH`, all will be fine:

Please try:
```
PATH=`dirname $LMOD_CMD`:$PATH python bootstrap_eb.py <prefix>
```

@fgeorgatos: `modulecmd` or `lmod` being available in `$PATH` is non-standard, it's a requirement specific to EasyBuild; we can probably avoid that requirement though, which requires parsing `type -f module` to figure out the path ourselves (probably not trivial)

**Comment by verdurin** [comment] 2015-12-05 08:50
@boegel - Yes, it works if I bodge `$PATH` manually.

It would be nice not to have to bother...

**Comment by fgeorgatos** [comment] 2015-12-05 16:31
+1 , to have it automatically as part of bootstrap; cheap fix, for less
questions in the future...
yet, is there any downside?

F.


On 5 December 2015 at 08:50, Adam Huffman <notifications@github.com> wrote:

> @boegel <https://github.com/boegel> - Yes, it works if I bodge $PATH
> manually.
>
> It would be nice not to have to bother...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hpcugent/easybuild-framework/issues/1500#issuecomment-162162127>
> .
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by boegel** [comment] 2015-12-12 09:53
I don't think there's a downside, it's just an attempt to automagically deal with the situation where there's no `lmod` available through `$LMOD_CMD` or `$PATH`.

It's a bit of a desperate attempt, but if it succeeds, it's useful.

Short term, making the bootstrap script aware of `$LMOD_CMD` should be easy, and very useful.

**Comment by wpoely86** [comment] 2015-12-16 08:46
Doesn't setting `EASYBUILD_MODULE_TOOL=Lmod` also work?

**Comment by boegel** [comment] 2015-12-16 08:51
It should (and that's also required by EasyBuild itself, since `EnvironmentModulesC` is still the default).

But we can do better, we can auto-detect based on the `module` function (as a fallback?).

**Comment by boegel** [comment] 2016-03-09 15:21
kind of a duplicate of #1347

@verdurin: shall we close #1347 (there's more relevant info in here w.r.t. parsing `module` imho)

**Comment by boegel** [comment] 2016-05-10 19:38
step forward: bootstrap script is now aware of `$LMOD_CMD`, cfr. #1736
(but doesn't check `module` function yet)

**Comment by Flamefire** [comment] 2020-02-24 12:12
As the docu is pretty clear on what needs to be in PATH now I feel this should be closed

**Comment by boegel** [comment] 2020-03-01 13:58
That's actually not needed anymore, since both the bootstrap script and EasyBuild itself now also pick up on `$LMOD_CMD` (which is defined when the environment is properly set up to use Lmod)...

**Closed by boegel** 2020-03-01 13:58 UTC
Labels: problem report
